import { allLessons } from "../content/courses.js";
import { drills } from "../content/drills.js";
import { BoardView } from "../ui/board-view.js";
import { DrillSession } from "../training/drill-session.js";
import { ReviewSession } from "../training/review-session.js";
import { START_FEN } from "../chess/game-state.js";

export class AppShell {
  constructor(app,root=document.body){this.app=app;this.root=root;this.board=null;this.session=null;this.root.addEventListener("rebel:navigate",e=>this.renderPage(e.detail));}
  mount(){this.root.innerHTML=`<div class="rebel-shell"><aside class="rebel-sidebar" aria-label="Rebel Chess navigation"><div class="rebel-brand"><strong>REBEL</strong><span>CLASSIC CHESS</span></div><nav class="rebel-nav">${["home","board","courses","trainer","analysis","progress"].map(id=>`<button data-page="${id}" class="rebel-nav-item"><span>•</span><b>${id[0].toUpperCase()+id.slice(1)}</b></button>`).join("")}</nav><div class="rebel-sidebar-card"><b>Learn + train</b><span>${allLessons().length} lessons · ${drills.length} drills</span></div></aside><main class="rebel-main"><header class="rebel-header"><div><span class="eyebrow">REBEL CHESS</span><h1 id="pageTitle">Home</h1></div><div class="rebel-status" id="engineStatus">Engine connected</div></header><section id="rebel-page" class="rebel-page"></section></main></div>`;this.root.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>this.app.router.go(b.dataset.page));this.app.router.go("home");}
  renderPage(id){
    const page=this.root.querySelector("#rebel-page");this.root.querySelector("#pageTitle").textContent=id[0].toUpperCase()+id.slice(1);this.session=null;this.board=null;
    if(id==="home")return this.home(page);
    if(id==="board")return this.workspace(page,"Play Board");
    if(id==="courses")return this.courses(page);
    if(id==="trainer")return this.trainer(page);
    if(id==="analysis")return this.analysis(page);
    return this.progress(page);
  }
  home(page){page.innerHTML=`<div class="hero-card"><span class="eyebrow">REBEL WORKSPACE</span><h2>Learn chess. Play chess. Become dangerous.</h2><p>One board foundation powers play, lessons, training and analysis.</p><button class="primary" data-page="courses">Start learning</button></div><div class="metric-grid"><div><b>${allLessons().length}</b><span>Lessons</span></div><div><b>${drills.length}</b><span>Drills</span></div><div><b>SF</b><span>Engine</span></div></div>`;page.querySelector("[data-page]").onclick=()=>this.app.router.go("courses");}
  workspace(page,label){page.innerHTML=`<div class="section-heading"><div><span class="eyebrow">BOARD</span><h2>${label}</h2></div><button class="secondary" data-page="analysis">Analyze position</button></div><div class="rebel-workspace"><div id="rebel-board-mount"></div><aside class="rebel-panel"><h3>${label}</h3><p>Make legal moves on the shared board.</p><div id="workspaceMoves"></div></aside></div>`;this.board=new BoardView({state:this.app.game});this.board.onMove=()=>{page.querySelector("#workspaceMoves").textContent=this.app.game.history().join(" ");};this.board.mount(page.querySelector("#rebel-board-mount"));page.querySelector("[data-page]").onclick=()=>this.app.router.go("analysis");}
  courses(page){page.innerHTML=`<div class="section-heading"><div><span class="eyebrow">LEARN</span><h2>Courses</h2></div><span>${Object.keys(this.app.courses).length} courses</span></div><div class="course-grid">${Object.values(this.app.courses).map(c=>`<article class="course-card"><span class="course-tag">${c.category}</span><h3>${c.title}</h3><p>${c.chapters.length} chapters · ${c.chapters.reduce((n,x)=>n+x.lessons.length,0)} lessons</p><button class="secondary" data-course="${c.id}">Open course</button></article>`).join("")}</div><div id="lesson-panel"></div>`;page.querySelectorAll("[data-course]").forEach(b=>b.onclick=()=>this.openCourse(page,b.dataset.course));}
  openCourse(page,id){const course=this.app.courses[id], lessons=course.chapters.flatMap(c=>c.lessons);page.querySelector("#lesson-panel").innerHTML=`<div class="hero-card"><h3>${course.title}</h3><div class="lesson-list">${lessons.map((l,i)=>`<button class="secondary lesson-choice" data-index="${i}">${i+1}. ${l.title}</button>`).join("")}</div><div id="lesson-workspace"></div></div>`;page.querySelectorAll(".lesson-choice").forEach(b=>b.onclick=()=>this.openLesson(page,lessons[+b.dataset.index],lessons,+b.dataset.index));}
  openLesson(page,lesson,lessons,index){const mount=page.querySelector("#lesson-workspace");mount.innerHTML=`<h4>${lesson.title}</h4><p>${lesson.description}</p><div id="lesson-board"></div><button class="primary" data-next>${index<lessons.length-1?"Next lesson":"Finish course"}</button><div id="lesson-status"></div>`;this.board=new BoardView({state:this.app.game});this.board.setPosition(lesson.fen);this.board.onMove=()=>page.querySelector("#lesson-status").textContent="Move recorded. Try the position again or continue.";this.board.mount(mount.querySelector("#lesson-board"));page.querySelector("[data-next]").onclick=()=>{if(index<lessons.length-1)this.openLesson(page,lessons[index+1],lessons,index+1);else page.querySelector("#lesson-status").textContent="Course section complete.";};}
  trainer(page){page.innerHTML=`<div class="section-heading"><div><span class="eyebrow">TRAIN</span><h2>Trainer</h2></div><span>Stockfish-powered targets</span></div><div class="course-grid">${drills.map(d=>`<article class="course-card"><span class="course-tag">${d.category}</span><h3>${d.title}</h3><p>${d.description}</p><button class="secondary" data-drill="${d.id}">Start drill</button></article>`).join("")}</div><div id="trainer-workspace"></div>`;page.querySelectorAll("[data-drill]").forEach(b=>b.onclick=()=>this.startDrill(page,b.dataset.drill));}
  async startDrill(page,id){const drill=drills.find(d=>d.id===id), mount=page.querySelector("#trainer-workspace");mount.innerHTML=`<div class="hero-card"><h3>${drill.title}</h3><p id="trainer-status">Finding the Stockfish target…</p><div id="trainer-board"></div><button class="secondary" data-retry>Retry</button></div>`;this.session=new DrillSession(drill,this.app.engine);this.board=new BoardView({state:this.session.state});this.board.onMove=async move=>{
 const played=move.from+move.to+(move.promotion||"");
 if(!this.session.target){mount.querySelector("#trainer-status").textContent="Still analyzing the target…";return;}
 if(played===this.session.target){this.session.status="Correct — Stockfish confirms the best move.";this.app.storage.updateProgress({tactics:this.app.storage.progress().tactics+1,xp:this.app.storage.progress().xp+10});}
 else{this.session.status="Legal move, but not the target. Try again.";this.session.state.reset(drill.fen);this.board.render();}
 mount.querySelector("#trainer-status").textContent=this.session.status;
};this.board.mount(mount.querySelector("#trainer-board"));try{await this.session.prepare();mount.querySelector("#trainer-status").textContent=this.session.status;}catch(e){mount.querySelector("#trainer-status").textContent="Engine unavailable — retry when Stockfish is ready.";}}
  async analysis(page){page.innerHTML=`<div class="section-heading"><div><span class="eyebrow">ANALYSIS</span><h2>Game Review</h2></div><button class="secondary" data-new>New position</button></div><div class="rebel-workspace"><div id="analysis-board"></div><aside class="rebel-panel"><h3>Position report</h3><p id="analysis-status">Play moves, then request an engine review.</p><button class="primary" data-review>Analyze position</button><div id="analysis-report"></div></aside></div>`;this.board=new BoardView({state:this.app.game});this.board.mount(page.querySelector("#analysis-board"));page.querySelector("[data-new]").onclick=()=>{this.app.game.reset();this.board.render();};page.querySelector("[data-review]").onclick=async()=>{const moves=this.app.game.history();if(!moves.length){page.querySelector("#analysis-status").textContent="Make at least one move first.";return;}page.querySelector("#analysis-status").textContent="Analyzing…";const session=new ReviewSession(START_FEN,moves,this.app.engine);try{const results=await session.run();page.querySelector("#analysis-report").innerHTML=results.map(r=>`<div><b>${r.ply}. ${r.move}</b> — ${r.classification} · best ${r.best}</div>`).join("");page.querySelector("#analysis-status").textContent="Review complete.";this.app.storage.updateProgress({analysis:this.app.storage.progress().analysis+1,xp:this.app.storage.progress().xp+5});}catch(e){page.querySelector("#analysis-status").textContent="Analysis cancelled or unavailable.";}};}
  progress(page){const p=this.app.storage.progress();page.innerHTML=`<div class="hero-card"><span class="eyebrow">PROGRESS</span><h2>Keep building your game.</h2><div class="metric-grid"><div><b>${p.xp}</b><span>XP</span></div><div><b>${p.lessons}</b><span>Lessons</span></div><div><b>${p.tactics}</b><span>Training</span></div><div><b>${p.analysis}</b><span>Analyses</span></div></div></div>`;}
}